### ISSUE TITLE
BlacksmithsTools does not load properly in Valheim 0.207.20

### ISSUE THREAD

**Issue by templeofxor** [GoldenJude/BlacksmithTools#1]
Copied post by DerSpieleentwickler from Nexus 
[https://www.nexusmods.com/valheim/mods/566?tab=bugs](https://www.nexusmods.com/valheim/mods/566?tab=bugs)

22 March 2022, 3:44PM

> Hey, since last Valheim patch we got quite some reports of players telling us the Beast Tribes Mod is not working properly (Hiding does not work). Today I got the time to take a look into this and as I rely on the BlachsmithsTools, which causes this exception (I think this is why my mod does not work as intended):
> Error : Unity Log] ArgumentException: Undefined target method for patch method static bool BlacksmithTools.BodypartSystem::UsesHairPatch(VisEquipment instance, Boolean& result)Stack trace:
> HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> Rethrow as HarmonyException: Patching exception in method null
> HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable1[T] sequence, System.Action1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> BlacksmithTools.Main.Start () (at < a3eae35a29cc459ba402d6e7e1171087 >:0)

**Comment by GoldenJude** [comment]
Nexus release will not be updated.
