### ISSUE TITLE
Error when loading Blacksmith tools.

### ISSUE THREAD

**Issue by jdalfonso4341** [GoldenJude/BlacksmithTools#3]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BlacksmithTools.BoneReorder.AttachArmorPatch (VisEquipment __instance, System.Collections.Generic.List`1[T] __result, System.Int32 itemHash) (at <b12dd16ce1fd41dea22f5c5818688fb0>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::AttachArmor>(VisEquipment,int,int)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::SetUtilityEquiped>(VisEquipment,int)
VisEquipment.UpdateEquipmentVisuals () (at <0a1a436be26b421bb46752e573a7aa2f>:0)
VisEquipment.UpdateVisuals () (at <0a1a436be26b421bb46752e573a7aa2f>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::Start>(VisEquipment)

**Comment by Unforgiven13** [comment]
Same error here as well.
I think it's affected by RRRNPCs and especially from AdvancedCustomAttacks.
[LogOutput.log](https://github.com/GoldenJude/BlacksmithTools/files/11069115/LogOutput.log)
